# This will build for the target platform
# The python must match that (i.e., 64 bit platforms need 64 bit pythons by default)
# You can specify which python to use by setting the environment variable PYO3_PYTHON to point to that python
# For example
#   env PYO3_PYTHON=C:/usr/bin/python32-3.8 cargo build --target i686-pc-windows-msvc --release

[package]
name = "MathCatForPython"
version = "0.7.6-beta.9"  # on github, this will be replaced by the current MathCAT version
authors = ["Neil Soiffer <soiffer@alum.mit.edu>"]
edition = "2024"
resolver = "2"    # allows different build dependency features


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libmathcat_py"
crate-type = ["cdylib"]

[dependencies]
# mathcat = { version = "=0.7.6-beta.9" }
mathcat = { path = "../MathCAT/" }  # local default; CI rewrites to git tag "latest"
# mathcat = { git = "https://github.com/NSoiffer/MathCAT", tag = "latest" }
pyo3 = { version = "0.27", features = ["extension-module", "abi3"] }

[build-dependencies]
zip = { version = "8.5", default-features = false, features = ["bzip2"] }
# mathcat = { version = "=0.7.6-beta.9", features = ["include-zip"] }
mathcat = { path = "../MathCAT/", features = ["include-zip"] }  # local default; CI rewrites to git tag "latest"
# mathcat = { git = "https://github.com/NSoiffer/MathCAT", tag = "latest", features = ["include-zip"] }



[profile.release]
lto = true
# opt-level = "z"  # Optimize for size.
